export const signInButton = 'a.login';
export const fieldEmail = 'input#email';
export const fieldPasswd = 'input#passwd';
export const submitLogin = 'button#SubmitLogin';
export const loginFail = 'div#center_column div.alert li';
export const loginSuccess = 'div#center_column p.info-account';
export const fieldSearch = 'form#searchbox input#search_query_top';
export const buttonSearch = 'form#searchbox button.button-search';
export const searchFail = 'div#center_column p.alert';
export const searchResultCard = 'ul.product_list li.first-in-line'
export const buttonGoCheckout = 'div#layer_cart div.button-container a.button'
export const searchResult = 'ul.product_list li.first-in-line a.product-name';
export const addToCart = 'a.ajax_add_to_cart_button';
export const addedToCartDiv = 'div#layer_cart';
export const addedToCart = 'div#layer_cart h2:first-of-type';
export const cartSummary = 'div#center_column h1#cart_title';
export const orderDetails = 'div#order-detail-content';
export const orderCartDelete = 'div#order-detail-content tr.first_item td.cart_delete';
export const cartEmpty = 'div#center_column p.alert';
export const buttonProceedCheckout = 'p.cart_navigation a.standard-checkout';
export const buttonProgressCheckout = 'p.cart_navigation button.button';
export const orderDetailsProdName = 'div#order-detail-content p.product-name';
export const totalProductsPrice = 'div#order-detail-content tr.cart_total_price td#total_product';
export const totalDeliveryPrice = 'div#order-detail-content tr.cart_total_delivery td#total_shipping';
export const methodPayment = 'div#HOOK_PAYMENT p.payment_module a.bankwire';
export const confirmOrderComplete = 'p.cheque-indent';
